### ISSUE TITLE
Improve  documentation

### ISSUE THREAD

**Issue by titilambert** [projectcalico/calico-mesos#14]
Hello !
I'm currently trying to get all working, but the doc is not so useful. Could it be more explicit ? Like what is the content of modules.json file ?
Also, I would like to write a tutorial (mesos-marathon-docker-mesosdns-calico)

Thanks

**Comment by spikecurtis** [comment]
@titilambert I'm with you that the docs need some love.  This is our newest integration, so things are coming together, but slowly.

Can we make this issue a little more directly actionable, like "Docs describe modules.json file", and then have another issue for the tutorial you'd like to see?

**Comment by titilambert** [comment]
Done !
I close this one :)
Thanks
