### ISSUE TITLE
Docs describe modules.json file

### ISSUE THREAD

**Issue by titilambert** [projectcalico/calico-mesos#16]
Hello,

As discuted #14 , this is the issue to detail the content of the modules.json file

Thanks

**Comment by djosborne** [comment]
Agreed! We should go into more detail on modules.json in #19

**Comment by djosborne** [comment]
We've merged our [documentation on modules.json](https://github.com/projectcalico/calico-docker/blob/master/docs/mesos/ManualInstallCalico.md#create-the-modulesjson-configuration-file)!
