### ISSUE TITLE
Use the latest calicoctl releases

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico-mesos#55]
Need to make sure our master instructions (in the calico-containers repo) reference the master calicoctl release.  Raising the issue here to ensure calico-mesos is compatible with the latest calicoctl.

**Comment by robbrockbank** [comment]
Ideally the master branch of the documentation should refer to the master release of calicoctl,
and then a particular branch of calico-containers will pin the current release of mesos to a particular version of calicoctl.

We'll need to update the master docs to point to the master calicoctl url.

**Comment by djosborne** [comment]
Closing, since calico-mesos no longer points to any particular calico release (except for in the calico-mesos release notes)
