### ISSUE TITLE
Inquiry:  Any way to programatically create Calico Nets?

### ISSUE THREAD

**Issue by andrewkrug** [projectcalico/calico-mesos#67]
I am using Calico along with DC/OS Mesosphere.  Installed from the universe repository.  Is there any way to programmatically create networks using the marathon or other API?

**Comment by caseydavenport** [comment]
To my knowledge, that isn't available yet but should be added to Marathon in an upcoming release.

@djosborne should have the details on this.

**Comment by djosborne** [comment]
Casey is correct, Marathon doesn't currently have the ability to create docker networks. I don't think it is currently on their radar either, could you raise an issue there to show interest?

**Comment by andrewkrug** [comment]
Tagged on a request to this thread. 

https://github.com/mesosphere/marathon/issues/3788

**Comment by djosborne** [comment]
I've been thinking about this a bit more, and I think the ability to create a network on the  fly would need to be introduced in Core Mesos before Marathon could support. 

Creation of a docker network requires a request to the Docker Engine on an agent which is configured with a cluster store. I don't think Marathon is capable of making such a request, and rather would need to ask Mesos to do it instead.

**Comment by andrewkrug** [comment]
I would love to support filing this as the proper pull request in the
proper place.  Care to collaborate on the description?

On Fri, Jun 3, 2016 at 1:36 PM, djosborne <notifications@github.com> wrote:

> I've been thinking about this a bit more, and I think the ability to
> create a network on the fly would need to be introduced in Core Mesos
> before Marathon could support.
>
> Creation of a docker network requires a request to the Docker Engine on an
> agent which is configured with a cluster store. I don't think Marathon is
> capable of making such a request, and rather would need to ask Mesos to do
> it instead.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/projectcalico/calico-mesos/issues/67#issuecomment-223688116>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACYve5Xd7pBGvs2n1UZoZgUt1HjQtWEFks5qIJBYgaJpZM4Irxr->
> .
>



-- 
Andrew J.Krug
541-708-1002

**Comment by andrewkrug** [comment]
I did find the following guide on IPAM and Marathon

https://docs.google.com/document/d/17mXtAmdAXcNBwp_JfrxmZcQrs7EO6ancSbejrqjLQ0g/edit#heading=h.ysz5lapiadp0

On Fri, Jun 3, 2016 at 3:04 PM, Andrew Krug <andrewkrug@gmail.com> wrote:

> I would love to support filing this as the proper pull request in the
> proper place.  Care to collaborate on the description?
>
> On Fri, Jun 3, 2016 at 1:36 PM, djosborne <notifications@github.com>
> wrote:
>
>> I've been thinking about this a bit more, and I think the ability to
>> create a network on the fly would need to be introduced in Core Mesos
>> before Marathon could support.
>>
>> Creation of a docker network requires a request to the Docker Engine on
>> an agent which is configured with a cluster store. I don't think Marathon
>> is capable of making such a request, and rather would need to ask Mesos to
>> do it instead.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/projectcalico/calico-mesos/issues/67#issuecomment-223688116>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ACYve5Xd7pBGvs2n1UZoZgUt1HjQtWEFks5qIJBYgaJpZM4Irxr->
>> .
>>
>
>
>
> --
> Andrew J.Krug
> 541-708-1002
>
>


-- 
Andrew J.Krug
541-708-1002

**Comment by djosborne** [comment]
Would be happy to collaborate, but I think we should do it on a fresh document, as the on you linked is focused on netmodules and has become a bit dated.

I'm going to give this some more thought before creating the document myself, but if you beat me to it, just post a link here so I can add my thoughts
