### ISSUE TITLE
calico mesos update

### ISSUE THREAD

**Issue by elppc** [projectcalico/calico-mesos#72]
Hi,
Any update on this project ? I am interested in testing IP per container on Mesos with Calico as a way to control network QoS and secure multi tenant cluster.
It seems DCOS is the preferred solution (from calico commits point of view) but it doesn't fit my needs.

**Comment by djosborne** [comment]
@elppc This repository is home to Calico's net-modules plugin. 

Mesos has deprecated net-modules as a networking plugin module in favor of the established CNI. Calico has a CNI plugin which is compatible with Mesos CNI networking hooks. Learn how to install and use it here: http://docs.projectcalico.org/v2.0/getting-started/mesos/installation/unified

**Comment by elppc** [comment]
sorry for the misunderstanding
